### ISSUE TITLE
你好,about页面如何配置呢?

### ISSUE THREAD

**Issue by ghost** [Lemonreds/hexo-theme-nayo#1]
这款主题简洁漂亮,我非常喜欢,打算用于自己的个人博客.

about怎么加呢,我在更目录的source放了,about文件夹,about文件夹放了inde.html,发现效果和你官网演示的不一样,我该怎么加about才合适呢?

谢谢你了,本人hexo 和 前端的小白.

**Comment by ghost** [comment]
还有我在根目录_config.xml中配置的title subtitle description author 等信息怎么没有出现在网站中?

**Comment by Lemonreds** [comment]
@ricardo0624  hexo默认不创建分类、标签、关于 所以你需要自己生成，如about页面，
1. 进入你的博客根目录 cd yourblog 
2. 执行命令 hexo new page about 
3. 修改about index.md 新憎layout为about 如
```
title: about
date: 2017-10-26 22:19:49
layout: about
//这里开始是你的具体about内容
```

为了便于填写 网站的 title subtitle description author 我放在了主题目录下的配置文件 
nayo/_config.xml

更多配置你看下ReadMe
http://synch.site/2017/10/26/README/

**Comment by ghost** [comment]
😄😄谢谢了,那个README还真没看
感谢你的秒回👏👏

**Comment by Lemonreds** [comment]
@ricardo0624 没关系 有什么问题尽管问 !

**Comment by ghost** [comment]
@Lemonreds 还有我在根目录_config.xml中配置的title subtitle description author 等信息怎么没有出现在网站中? 那这个呢

**Comment by Lemonreds** [comment]
在主题目录下的config.xml文件中配置！

**Comment by ghost** [comment]
@Lemonreds 但是配置了好像不生效,比如description,我试了另外一个主题的时候,它后把它解析成keywords,但是Nayo,我刚才配了title subtitle description author在主题目录下,好像被忽略了

**Comment by Lemonreds** [comment]
博客主目录下的config站点配置不会影响的 因为在主题中是直接读取主题目录下的config的 你配置好了后重新生成静态网页 hexo g
