### ISSUE TITLE
怎么修改中文

### ISSUE THREAD

**Issue by emodechengnuo** [Lemonreds/hexo-theme-nayo#11]
很喜欢这个主题。我看菜单中是有中文的，怎么修改？如果直接修改 menu会显示menu.名字。谢谢拉

**Comment by Lemonreds** [comment]
@emodechengnuo  在你的博客  `根目录下的_config.yml`  配置
 `language: zh-CN` 即可

**Comment by emodechengnuo** [comment]
非常感谢
