### ISSUE TITLE
Any plan to add disqus?

### ISSUE THREAD

**Issue by Godsenal** [Lemonreds/hexo-theme-nayo#12]
First of all, Thank you for your awesome theme!

Is there any plan to add the disqus comment system? 
I'm doing it manually by adding some code to comment.ejs. (I hope it's ok to add some code...)

**Comment by Lemonreds** [comment]
That is correct o add code in comment.ejs and I'll add the discus to the theme in these days! Thanks for your advice!

**Comment by Godsenal** [comment]
Thanks! I'm looking forward it. 😄
