### ISSUE TITLE
tag 应该为 tags

### ISSUE THREAD

**Issue by DanteAndroid** [Lemonreds/hexo-theme-nayo#13]
[这里](https://github.com/Lemonreds/hexo-theme-nayo/tree/master/layout )的文件，名称应该为复数。
我是发现标签页面显示不了才发现这个问题的。网上的教程是要创建一个名为`tags`的page，然后修改属性为：
```
title: Tags
type: "tags"
layout: "tags"
```
您写的layout文件名为tag，所以死活没效果。。。文档里也没有关于tags页面的说明

**Comment by Lemonreds** [comment]
@DanteAndroid  

你说得很对！其实不管是什么名称，layout会在主题文件中找到指定的文件生成静态页面，找不到则生成为post类型。

大部分主题用的都是 categories 和 tags，会考虑进行修改。

![image](https://user-images.githubusercontent.com/23014238/35916832-b8c6f774-0c46-11e8-95f3-164fbb64071f.png)

**Comment by DanteAndroid** [comment]
谢谢，我非常喜欢这个主题~挑了很久最后选择了这个

**Comment by kangxianying** [comment]
除了文件名字改, 其他地方还有需要修改的吗??? 我把layout里的tag文件改成了tags还是没效果~不知道还有哪里关联的
---解决了~..看完你写的文章之后~~

**Comment by JiuMingZhu** [comment]
在这里找到Tags不显示的解决办法了，喜欢你的主题！！！
