### ISSUE TITLE
好像用了这个主题很多人反应网站打开慢

### ISSUE THREAD

**Issue by DanteAndroid** [Lemonreds/hexo-theme-nayo#15]
貌似第一次打开之后，后面就很快了。
是不是跟主题有关？比如里面有什么需要翻墙的文件吗？我换了主题别人说可以打开了。。。

**Comment by Lemonreds** [comment]
@DanteAndroid 😄 这个问题我也注意到了！ 是代码的原因，一有空会进行优化的。
