### ISSUE TITLE
文章有序列表序号中断的问题

### ISSUE THREAD

**Issue by tzizi5566** [Lemonreds/hexo-theme-nayo#16]
你好作者，非常棒的一个主题，我已经在使用了。但最近写文章发现用MD的有序列表序号无法连续计数的问题如下图

![qq 20180212150017](https://user-images.githubusercontent.com/14107578/36086280-51086cd0-1006-11e8-9cc6-5155dab2d18d.png)
![qq 20180212150053](https://user-images.githubusercontent.com/14107578/36086281-514e99ee-1006-11e8-83f9-5f3eb2442a62.png)

有部分正常而部分又有问题，是我MD语法不正确还是其他问题？作者能帮忙看下吗

**Comment by Lemonreds** [comment]
@tzizi5566 具体原因可能和hexo的md解析有关，目前的解决方法就是给 无序列表 加个 tab 。

![image](https://user-images.githubusercontent.com/23014238/36086858-b088614e-1009-11e8-92fc-ce54f82a1a45.png)

**Comment by tzizi5566** [comment]
按作者的方法已经解决了 非常感谢
