### ISSUE TITLE
mobile-toggle not working 

### ISSUE THREAD

**Issue by padosum** [Lemonreds/hexo-theme-nayo#17]
Thank you for your beautiful themes... 👍 
But in the mobile version, left side toggle not working :disappointed_relieved:

![default](https://user-images.githubusercontent.com/6129764/36246866-0e5729d2-1275-11e8-823d-c528597a38db.PNG)

**Comment by Lemonreds** [comment]
oh....this is a bug after using the webpack, :laughing:  I will fix it as soon as possible, thanks for the feedback.
