### ISSUE TITLE
你好,fullScreen=true的情况下,浏览单个文章的时候出现水平滚动条(首页没有),能不能不出现?

### ISSUE THREAD

**Issue by ghost** [Lemonreds/hexo-theme-nayo#2]
感觉屏幕的分辨率(1600*900 无缩放)也不是太小,能放下,可否考虑下不出现水平滚动条?

**Comment by Lemonreds** [comment]
这个应该是一个bug 我中午回去看一下 谢谢你的反馈

**Comment by Lemonreds** [comment]
@ricardo0624 是布局写得太绝对的问题 准备重写 因为下午有课所以到晚上才能更新了 抱歉啦！:grin:

**Comment by ghost** [comment]
@Lemonreds 不用客气了,开原本就是付出,有小问题也很正常
