### ISSUE TITLE
404错误页面怎么添加？

### ISSUE THREAD

**Issue by ghost** [Lemonreds/hexo-theme-nayo#20]
假如失误打开页不存在，怎么添加错误界面？

**Comment by Lemonreds** [comment]
@923453645 在博客目录 /source 下添加 404.html  hexo -g 生成到public 推送到github上就可以。
注意 在404.html前加
`---`
`layout: false` 
`---`
防止被hexo解析

参考：https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/
