### ISSUE TITLE
搜索框乱码

### ISSUE THREAD

**Issue by DanteAndroid** [Lemonreds/hexo-theme-nayo#26]
![image](https://user-images.githubusercontent.com/10005563/38923767-e30f1cdc-432d-11e8-928e-c8d8b311f652.png)
如图，那个『&#x』

**Comment by DanteAndroid** [comment]
还有，以前可以选择代码块的主题色，现在好像不行了：
```
highlight_theme: 
    night
```

**Comment by Lemonreds** [comment]
@DanteAndroid  删除了一些配置，以最新的config为主.
