### ISSUE TITLE
打赏的二维码没有加载出来

### ISSUE THREAD

**Issue by PennySuu** [Lemonreds/hexo-theme-nayo#28]
![default](https://user-images.githubusercontent.com/11702194/39625459-1533fa80-4fd0-11e8-9c0a-d8c52b639cce.png)

**Comment by Lemonreds** [comment]
@PennySuu 应该是懒加载的原因

**Comment by istek** [comment]
这个主题很清爽，很喜欢。能否修复这个bug呢？

**Comment by Lemonreds** [comment]
@istek  示例网站上不会出现这个问题了。
