### ISSUE TITLE
建议集成hexo-generator-search搜索插件

### ISSUE THREAD

**Issue by jerry011235** [Lemonreds/hexo-theme-nayo#3]
你好，建议集成hexo-generator-search插件，关键字高亮。
另外在打开无目录的文章时，页面会有短暂的 显示目录，然后消失。

**Comment by Lemonreds** [comment]
@jerry011235  站内搜索可以加入 目录这个问题算是一个小bug 谢谢你的建议和反馈！

**Comment by jerry011235** [comment]
1.希望引入适合中文阅读的网页排版`typo.css`
https://typo.sofi.sh
2.能否支持双评论（LeanCloudt 和 Disqus），默认显示LeanCloudt ，点击按钮后在LeanCloudt 后面加载Disqus。参考 https://ehlxr.me/about

**Comment by Lemonreds** [comment]
1 文章内容排版我也一直想做优化 
2 disqus好像是被墙了吧？估计短期内不会添加

**Comment by jerry011235** [comment]
好的，还有就是当md文件只有二级目录（`##`）和三级目录（`###`）时，主题不会显示目录。除非把`##`替换成`#`，目录才能显示出来。

**Comment by Lemonreds** [comment]
是的 因为没有直接用hexo的辅助函数 需要一个 # 才会生成目录  h2h3 二级标题  h456 标题不识别
