### ISSUE TITLE
你好~~想插入视频在博客里,但是无法全屏~请问有什么方法吗??

### ISSUE THREAD

**Issue by kangxianying** [Lemonreds/hexo-theme-nayo#30]
<iframe width="560" height="315" src="https://www.youtube.com/embed/mJqUCHiF530" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

已经是allowfullscreen了..
可是全屏会出错,像这样:
![](https://i.imgur.com/3Kx4rsI.png)

**Comment by Lemonreds** [comment]
@kangxianying 可能是布局的原因？有空我看看吧。
