### ISSUE TITLE
search功能没起作用

### ISSUE THREAD

**Issue by JiuMingZhu** [Lemonreds/hexo-theme-nayo#35]
![](http://ouz2us6un.bkt.clouddn.com/18-6-29/48839734.jpg)
我在chrome里面调试了一下，好像input事件没触发
（也有可能是我调试的不对）

我是在windows上面编写的博客，然后把hexo文件夹用git同步到服务器上（themes文件夹下面你的主题也同步过去了）
然后在服务器上生成静态页面，最后用NGINX做的反向代理
请问会不会是这中间哪一步出问题了？
下面是我博客的地址
www.****.com 
***
在作者指引下问题解决了，博客就不贴了。>.<

**Comment by Lemonreds** [comment]
请问有安装相应插件并启用吗？参考示例博客的第一篇文章

**Comment by JiuMingZhu** [comment]
谢谢，是我没仔细看示例博客。安装完npm并在文件中配置后已经可以搜索了：）
