### ISSUE TITLE
How do I add "tags" page?

### ISSUE THREAD

**Issue by rikusen0335** [Lemonreds/hexo-theme-nayo#37]
I'm sorry I know exist the same issue, but I can't read Chinese, and I can't read them with some translator.
So, I want to know how to make it.
Can you tell me, anyone?

**Comment by Lemonreds** [comment]
@Rikusen0335  hi , you can try it as the following steps:

1: Generate the page
`cd yourblog
`
`
hexo new page  tags/about
`

2: Add 'layout' line to the index.md of the new page folder.

tag page : 
```
---
title: tags
layout: tag
---
```
about page:
```
---
title: about
layout: about
---
```

see:  http://synch.site/2018/02/08/hexo-theme-nayo/

**Comment by rikusen0335** [comment]
Thank you for answering!
