### ISSUE TITLE
Tags问题

### ISSUE THREAD

**Issue by ghost** [Lemonreds/hexo-theme-nayo#38]
一篇post可以添加多个tags吗？我在添加时生成的tags是这样的
![image](https://user-images.githubusercontent.com/13183806/42371705-d4bcbeb6-8142-11e8-919c-26c4ffb59482.png)

**Comment by ghost** [comment]
怎么让Qin Zhang和Published in 2016在两个方框内呢？

**Comment by Lemonreds** [comment]
@Attache 

![_20180706174554](https://user-images.githubusercontent.com/23014238/42372349-944673c0-8144-11e8-82bb-99d16def2f82.png)

我记得是这样 详情参考yaml语法

**Comment by ghost** [comment]
问题解决，谢谢～～✌️
