### ISSUE TITLE
Markdown序列的序号无法显示

### ISSUE THREAD

**Issue by Ivan-Fan** [Lemonreds/hexo-theme-nayo#43]
您好，我是用下面的方式书写序列
`1. 苹果`
`2. 梨子`
但是发现发布到网页之后序号不见了，请问怎么解决呢？

**Comment by Lemonreds** [comment]
@Ivan-Fan 数字加句号加空格 md语法不正确

**Comment by Ivan-Fan** [comment]
我的确使用数字加句号加空格的

**Comment by Ivan-Fan** [comment]
md文件和网页效果分别是这样
![default](https://user-images.githubusercontent.com/39240631/43263868-12d5512a-9117-11e8-8c86-b17e6c7c1b8e.png)
![default](https://user-images.githubusercontent.com/39240631/43263874-16de60cc-9117-11e8-82b9-84df14184ee9.png)

**Comment by Ivan-Fan** [comment]
请问有比较好的解决办法嘛？

**Comment by Lemonreds** [comment]
@Ivan-Fan 我很难定位原因...你留个邮箱 我发实例网站的md文件给你

**Comment by Ivan-Fan** [comment]
好的，我的邮箱是ivanyangfan09@126.com。麻烦啦 @Lemonreds

**Comment by Ivan-Fan** [comment]
不好意思再打扰您，在文章排版的article里面有一部分关于ordered list的说明，md文件里是一个有序列表，但网页上面的序号就消失了，如下图：
![default](https://user-images.githubusercontent.com/39240631/43266243-7894bf72-911d-11e8-82bf-a9628c9f6ad2.png)
![default](https://user-images.githubusercontent.com/39240631/43266249-79f9a850-911d-11e8-941c-228d97f4ce84.png)
想问一下有办法让序号显示出来嘛？ @Lemonreds

**Comment by Lemonreds** [comment]
@Ivan-Fan 我晚上回去才看一下 感觉是个bug

**Comment by Ivan-Fan** [comment]
好的，谢谢哈

**Comment by Lemonreds** [comment]
@Ivan-Fan 已经修复 是代码的问题 我还以为是写法有误 :laughing:  你可以只替换source目录更新。
