### ISSUE TITLE
Categories可以显示多级分类吗？

### ISSUE THREAD

**Issue by Ivan-Fan** [Lemonreds/hexo-theme-nayo#44]
Nayo是一个很棒的主题，一上手就很喜欢！但平时比较习惯用多级分类，不知道Nayo的categories是否也能设计成这样的呢？效果类似于下图：
![default](https://user-images.githubusercontent.com/39240631/43397757-7c4d3266-9438-11e8-89bc-55c49a2c83fa.jpg)

**Comment by Lemonreds** [comment]
@Ivan-Fan 不支持多级分类呀 因为我觉得太多余了。

**Comment by Ivan-Fan** [comment]
好吧。不过如果能实现的话还是希望有大神指点一下 : P

**Comment by Lemonreds** [comment]
@Ivan-Fan 实现不是很难 具体有几级分类？

**Comment by Ivan-Fan** [comment]
2级就可以了

**Comment by Ivan-Fan** [comment]
悄悄问一下，从技术上来说categories最多可以实现几级呢？

**Comment by Lemonreds** [comment]
看hexo怎么处理的了 理论上没有限制

**Comment by Ivan-Fan** [comment]
好嘞，下次有机会自己一定好好学一学 : )

**Comment by Ivan-Fan** [comment]
期待可以在您方便的时候指点一下 : )或者可以教一下大概的步骤，我来学着改一改。麻烦您了 @Lemonreds

**Comment by Lemonreds** [comment]
参考hexo官方文档里的category修改主题布局文件里面使用到的地方 最近比较忙 还没有抽空出来做这个修改…

**Comment by Ivan-Fan** [comment]
没事儿，您先忙，我去试着看看hexo官方文档 : p

**Comment by Ivan-Fan** [comment]
我更新了您最近发布的版本，但是发现categories无法显示了，不知道是什么原因。。

**Comment by Lemonreds** [comment]
具体是哪个界面的内容…

**Comment by Ivan-Fan** [comment]
分类的界面里面没有内容了
![d2hvf2yjam ghbvkid wcl](https://user-images.githubusercontent.com/39240631/43989786-49b13786-9d83-11e8-88c8-ea9d1c319b96.png)

**Comment by Lemonreds** [comment]
这个页面是没有内容的！需要重写categories.ejs

**Comment by Ivan-Fan** [comment]
我不太会。。具体怎么修改呢？

**Comment by Lemonreds** [comment]
参考#36 具体css类名不用修改

**Comment by Ivan-Fan** [comment]
如果想实现多级分类的话，需要在他的基础上再加一些什么呢？

**Comment by srzer** [comment]
多级分类这样写即可

<section>

  <% if( is_category()){ %>

  	<span class="page-title"><%=  "# "+ page.category %></span>

  	 <% page.posts.each(function (post) { %>  

        <%- partial('_partial/item',{post:post}) %>       

  	 <% }) %> 	
  <%}else {%>    
      
        <span class="page-title"><%=  __('Page.Categories') %></span> 
        
        
          <% if (site.categories.length){ %>
          <div class="widget tag">
          <%- list_categories(site.categories) %> 
          </div>
          <% } %>

    <%}%>	    
</section>
