### ISSUE TITLE
你好，请问每篇博文上边的访问量是怎么设置的呢？

### ISSUE THREAD

**Issue by fanlinxi** [Lemonreds/hexo-theme-nayo#49]

**Comment by Lemonreds** [comment]
@fanlinxi  不支持这个哦 ，因为是静态网页，要支持的话需要第三方服务，比如 leancloud .

**Comment by popmum** [comment]
@Lemonreds 好的谢谢，主要是看见你的主题上边有访问量，想问下，请问你用的就是leancloud吗？

**Comment by Lemonreds** [comment]
@fanlinxi 噢 那个是文章字数的统计

**Comment by popmum** [comment]
@Lemonreds  好吧，我没看出来o(╥﹏╥)o
