### ISSUE TITLE
能否将示例网站的md贴出

### ISSUE THREAD

**Issue by wakefun** [Lemonreds/hexo-theme-nayo#5]
能否将[示例网站](http://synch.site/)中的测试md文件都贴出来，这样方便markdown新手对比纠错，麻烦了

**Comment by Lemonreds** [comment]
我打包一份发你邮箱吧！

**Comment by wakefun** [comment]
非常感谢！badaoshen@outlook.com

**Comment by Lemonreds** [comment]
不用客气 已发送
