### ISSUE TITLE
你好请问主页上的跳转链接图片(头像底下的图片)如何更换或者是添加新的？

### ISSUE THREAD

**Issue by fanlinxi** [Lemonreds/hexo-theme-nayo#50]
---来自弱鸡的提问(T＿T)

**Comment by Lemonreds** [comment]
因为图标是事先从iconfont下载的 所以就那么多 扩展的话需要再加图标 你需要增加什么类型的链接

**Comment by popmum** [comment]
是这样的，我找到了hexo-theme-nayo\src\css\style.styl和hexo-theme-nayo\src\css\fonts\iconfont.svg以及www.iconfont.cn这个网站，但是我不会改这种css样式o(╥﹏╥)o，我想添加网易云音乐和CSDN，其他的链接我都没有-_-||

**Comment by Lemonreds** [comment]
@fanlinxi iconfont上有一个项目用来存储icon，每次添加新的icon，都需要拉取下来新的 svg之类的文件到主题才可以。今晚会添加然后更新主题 :smiley:

**Comment by popmum** [comment]
好的，谢谢你了(๑¯∀¯๑)，辛苦了
