### ISSUE TITLE
怎么设置一页文章的数目呢

### ISSUE THREAD

**Issue by xieyezi** [Lemonreds/hexo-theme-nayo#51]
我现在已经累计了七篇文章了，但是没有自动分页，所有的文章全部在一页。我看您的展示，六篇文章就自动归为第一页了？然后还可以点击下一页。

**Comment by Lemonreds** [comment]
@xieyezi 修改根目录下的_config.yml 没记错的话分页字段叫 per_page ？修改完成后重启hexo应该就能看到修改了。

**Comment by xieyezi** [comment]
ok解决了，谢谢大佬！
