### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jerry011235** [Lemonreds/hexo-theme-nayo#6]
1.使用手机真机测试，导航栏（三横杆）点开后，本应出现`X`按钮，结果X浏览器和米侠浏览器不显示，firefox，夸克浏览器正常，不知道为什么？
2.侧边栏侧边栏sidebar: enable: false后，搜索按钮没有了，是否考虑将搜索按钮调到“首页、分类”那一栏？
3.导航栏（三横杆）点开后，能否[点击页面其他地方关闭菜单](https://www.zhihu.com/question/26391484)。

**Comment by Lemonreds** [comment]
1 这个问题可能很难解决，我会研究一下
2 搜索算是sidebar的一个部件 隐藏了sidebar就会隐藏 有考虑过加在Menu 但怕看起来太臃肿 一直想找一个合适的位置放
3 不错的建议 会加入

**Comment by emuoiea** [comment]
想问一下作者，归档页面的文章数量是如何自定义的呀，找了相关页面的参数未找到

**Comment by Lemonreds** [comment]
@zq520111 在根目录下config 有个Pagination可以配置，categories暂不支持。

**Comment by emuoiea** [comment]
tag页面代码的第十九行多了一个%>

**Comment by Lemonreds** [comment]
ok
