### ISSUE TITLE
不能正确解析markdown文档

### ISSUE THREAD

**Issue by xieyezi** [Lemonreds/hexo-theme-nayo#61]
我正常的写文档，没有使用代码标签,如图:
![image](https://user-images.githubusercontent.com/16821989/48545639-5845ab00-e901-11e8-818e-2fbd16039ea8.png)

但是打开浏览器预览，就会出现这样的情况,如图：
![image](https://user-images.githubusercontent.com/16821989/48545703-84f9c280-e901-11e8-9e6e-505c6285a17d.png)

可以看到，我写的段落，居然被自动解析成代码段了?

**Comment by Lemonreds** [comment]
@xieyezi 
hi,
空格缩进会解析成代码段，删除段落前空格就能解决问题了。
