### ISSUE TITLE
'OLDER'与'NEWER'的顺序问题

### ISSUE THREAD

**Issue by szz1204233** [Lemonreds/hexo-theme-nayo#63]
您好，是否可以将前/后一篇文章的按钮位置相对固定？
例如，目前版本，当处于最后一篇文章时 OLDER 会显示在左侧，而在其余文章时 OLDER 按钮皆在右侧
如果可以改为 OLDER 一直在左侧，个人觉得这样操作起来方便一些

**Comment by Lemonreds** [comment]
@szz1204233 
可以进行修改，最快要明天吧。
