### ISSUE TITLE
建议mob分享插件启用https

### ISSUE THREAD

**Issue by wakefun** [Lemonreds/hexo-theme-nayo#7]
在mob的官方案例中目前还是写的HTTP脚本链接，但经测试mob分享脚本已支持HTTPS，对于开启了HTTPS的网站在引用HTTP脚本会被浏览器主动拦截而导致分享功能不可用，此处改成https即可
![mob-link](https://user-images.githubusercontent.com/23612126/33001340-3bf1d94a-cde8-11e7-879a-338d88465f59.png)

**Comment by Lemonreds** [comment]
ok！ 谢谢你的建议
