### ISSUE TITLE
首页无法渲染数学公式

### ISSUE THREAD

**Issue by imhdx** [Lemonreds/hexo-theme-nayo#73]
post点进去后可以正常渲染，但从主页看，摘要部分的公式没有被渲染。对比next主题，post和主页的摘要部分都可以渲染。我尝试将hexo更新到最新版本，nayo也用的最新主题，都没有解决。求教大佬我应该怎么办？

**Comment by Lemonreds** [comment]
@imhdx 极有可能是主页没有引入库，我过几天才有空看看

**Comment by Lemonreds** [comment]
fix
