### ISSUE TITLE
导航栏的标签、关于页面找不到显示404

### ISSUE THREAD

**Issue by YuPeng1115** [Lemonreds/hexo-theme-nayo#74]
求作者解决一下该问题[https://yupeng1115.github.io/](url)，不知道该页面是否能调整language属性，最好是能选择中文简体，英文，中文繁体选项

**Comment by Lemonreds** [comment]
@YuPeng1115 标签页配置参考说明文档 https://lemonreds.github.io/2018/10/01/hexo-theme-nayo/ ， 语言选项修改根目录 _config.xml （非主题目录下）language 选项

**Comment by YuPeng1115** [comment]
谢谢作者，已得到解决，都怪没好好看说明文档
