### ISSUE TITLE
代码高亮，粗体等无法显示

### ISSUE THREAD

**Issue by car0ta** [Lemonreds/hexo-theme-nayo#77]
在某一行中插入的代码，类似于：`hexo`，好像没法显示，或者颜色很浅以至于不突出，还有markdown加粗字体也没法显示。请问您这个问题怎么解决呢？十分感谢！

**Comment by Lemonreds** [comment]
@car0ta 行内代码是有样式的，只是比较浅。加粗字体的话也可以直接修改样式，你可以尝试自己修改一下，难度不大的。

**Comment by car0ta** [comment]
好的谢谢
