### ISSUE TITLE
关于SEO优化问题怎么解决

### ISSUE THREAD

**Issue by YuPeng1115** [Lemonreds/hexo-theme-nayo#78]
description
keywords
在HEXO的_config.yml的Site设置了，博客的head标签里并没有显示网站描述和关键词

**Comment by Lemonreds** [comment]
@YuPeng1115  这部分确实没有功能，可以修改以下模板文件完成：
https://github.com/Lemonreds/hexo-theme-nayo/blob/master/layout/_partial/head.ejs
