### ISSUE TITLE
Donate bug

### ISSUE THREAD

**Issue by emuoiea** [Lemonreds/hexo-theme-nayo#8]
I didn't change anything about the donate module except the donate img,but I can't switch the two donate images..don't know the reason.

**Comment by Lemonreds** [comment]
@zq520111  问题解决了吗？

**Comment by emuoiea** [comment]
其他页面的没有问题，关于页面还是不能切换

**Comment by Lemonreds** [comment]
@zq520111 about/index.md增加了正确的layout吗？


title: about
date: 2017-10-15 23:32:49
layout: about
