### ISSUE TITLE
首页内容能显示长度嘛

### ISSUE THREAD

**Issue by ciweigg** [Lemonreds/hexo-theme-nayo#9]
现在所有文章内容都显示主页了 能设置只显示多少字嘛

**Comment by Lemonreds** [comment]
@ciweigg 在你的post里这样写：

`<!-- more -->`

来分隔 摘要 内容

**Comment by ciweigg** [comment]
![image](https://user-images.githubusercontent.com/31340264/34031069-a2f8ee8c-e1aa-11e7-8182-4cf50ba0fb65.png)

这样吗 不行啊？

**Comment by Lemonreds** [comment]
因为之前用手机打的 那个more标签被隐藏了 重新修改了下 你看下👆

**Comment by ciweigg** [comment]
可以了，谢谢，能加个好友么 qq 有问题交流方便点哈

**Comment by Lemonreds** [comment]
实际网站about页上有 就不留在这里了 ：）
